### ISSUE TITLE
wrong parsing of nested lists 

### ISSUE THREAD

**Issue by freylax** [kubkon/zig-yaml#23]
When parsing a list of maps and the last item of an map contains an non bracketed list the next outer list item will be intermixed with the inner one:
```yaml
- l: 
  - a
- l:
  - b
```
will result in:
```yaml
- l: [ a, l: [ b ] ]
```
instead of
```yaml
- l: [a]
- l: [b]
 ```

**Comment by freylax** [comment]
Also hyphened nested lists do not work as expected.

**Comment by freylax** [comment]
I added support for nested lists, but need help to create an pull request
The repo https://github.com/nodecum/zig-yaml contains the changes.

**Comment by leap0x7b** [comment]
Bro how did you not know how to pull request? Just go to https://github.com/kubkon/zig-yaml/compare and that's it. It's that easy.

**Comment by freylax** [comment]
Dear Jakub Konka,
I hope I did it all right now. Learnd git a bit more, thanks!
