### ISSUE TITLE
Log output by default

### ISSUE THREAD

**Issue by RobertWHurst** [kubkon/zig-yaml#9]
Hi there, firstly thanks for sharing your lib. It's pretty nice.

I have a question, I'm currently working on a tool for developers and was thinking I would use your lib for reading the config. During development I noticed that zig-yaml logs a lot of debug information. I understand this is helpful when developing the library, but it's making the stdout for my program a bit noisy. I've thought about excluding the scopes you are using for your loggers, but I wanted to ask you what you recommend I do first. If I want to mute zig-yaml what do you recommend?

**Comment by kubkon** [comment]
Hey @RobertWHurst! Thanks for the kind words! Re logging the output, I assume you are pulling the lib as a Zig package, am I right? In this case, in your main module, you can overwrite the `fn log(...)` function where you can explicitly control which log-scopes you want excluded and under what conditions. For example, have a look at how it's done for the `zld` linker:

[zld/src/main.zig#L19-L51](https://github.com/kubkon/zld/blob/3bd5d3e9fdb18e2c0e1dc53e076e5d1fb4301385/src/main.zig#L19-L51)

**Comment by Arnau478** [comment]
The scopes are pretty general. I don't want to stop using the "parse" scope in my project...
